# Generated by Django 4.2.7 on 2023-11-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordservicepair',
            name='encrypted_password',
            field=models.BinaryField(),
        ),
    ]
