name: password_manager workflow

on:
    pull_request:
        branches:
            - main
            - dev
    push:
        branches:
            - main
            - dev
        paths-ignore:
            - "README.md"

jobs:
    tests:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: github_actions_db
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: run migrations
              run: |
                export SECRET_KEY=${{ secrets.SECRET_KEY }}
                cd password_manager
                python manage.py makemigrations
                python manage.py migrate
            - name: run tests
              run: |
                export SECRET_KEY=${{ secrets.SECRET_KEY }}
                cd password_manager
                python -m flake8 --exclude migrations,settings.py --ignore I001,I003,I004
                pytest
    push_new_image_to_dockerhub:
        name: Push new image to dockerhub
        runs-on: ubuntu-latest
        needs: tests
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Docker buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: push
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/password_manager:latest
                file: Dockerfile
